server:
  port: '@server.port@'
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev
kontur-focus:
  token: 3208d29d15c507395db770d0e65f3711e40374df
da-data:
  token: 27a1864e226f61f145ca150b5b64a378af1da650
